name: CI

on:
  push:
    branches:
      - master

jobs:
  unit-php:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Cache dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-npm-${{ hashFiles('package-lock.json') }}

      - name: NPM Install
        run: npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'

      - name: Create .wp-env.override.json
        run: |
          touch .wp-env.override.json
          echo '{"config": {"WP_DEBUG": true, "SCRIPT_DEBUG": true, "MANDRILL_API_DEV_KEY":"${{ secrets.MANDRILL_API_DEV_KEY }}"}}' >> .wp-env.override.json

      - name: Run Unit Tests
        run: |
          npm run wp-env start
          npm run wp-env run composer 'install --no-interaction'
          npm run wp-env run phpunit 'phpunit -c /var/www/html/wp-content/plugins/mandrill-mail/phpunit.xml.dist --verbose'
